version: "3.9"
services:
  project_name_api_druid_entity:
    profiles: ["api"]
    image: project_name_api_druid:entity
    container_name: project_name_api_druid_entity
    hostname: project_name-api-druid-entity
    build:
      context: ./api/api-druid/entity
      args:
        poetry_version: "1.3.2"
    ports:
      - 8000:8000
    networks:
      - project_name_default
    restart: always
