repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/econchick/interrogate
    rev: 1.7.0
    hooks:
      - id: interrogate
        pass_filenames: false
        args:
          - --fail-under=100
          - --ignore-private
          - --ignore-magic
          - --verbose
          - src/opendataframework/component.py
          - src/opendataframework/config.py
          - src/opendataframework/context.py
          - src/opendataframework/entity.py
          - src/opendataframework/layer.py
          - src/opendataframework/logger.py
          - src/opendataframework/namespace.py
          - src/opendataframework/pipeline.py
          - src/opendataframework/project.py
          - src/opendataframework/repository.py
          - src/opendataframework/service.py
          - src/opendataframework/task.py
          - src/opendataframework/view.py

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.4
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
