version: "3.9"
services:
  project_name_api_json_kafka_entity:
    profiles: ["api"]
    image: project_name_api_json_kafka:entity
    container_name: project_name_api_json_kafka_entity
    hostname: project_name-api-json-kafka-entity
    build:
      context: ./api/api-json-kafka/entity
      args:
        poetry_version: "1.3.2"
    ports:
      - 8000:8000
    networks:
      - project_name_default
    restart: always
