version: "3.9"
services:
  project_name_openwebui:
    profiles: ["utility"]
    image: project_name:openwebui
    container_name: project_name_openwebui
    hostname: project_name-openwebui
    tty: true 
    build: 
      context: ./
      dockerfile: utility/openwebui/Dockerfile
    ports: 
      - 3000:8080
    volumes:
      - utility/openwebui/mnt:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - project_name_default
    environment:
      # - OLLAMA_BASE_URL=http://host.docker.internal:11434
      # - ENV=dev  # enables /docs endpoint
    restart: unless-stopped
