version: "3.9"
services:
  project_name_entity_inference:
    profiles: ["api"]
    image: project_name:entity_inference
    container_name: project_name_entity_inference
    hostname: project_name-entity-inference
    build:
      context: ./api/inference/entity
      args:
        poetry_version: "1.3.2"
    ports:
      - 8000:8000
    networks:
      - project_name_default
    restart: always
